// ============================================================
// ResourcesScreen — resource library backed by API
// ============================================================

import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { TtsButton } from '@/components/TtsButton';
import { resourcesApi, translations } from '@/lib/api';
import { useApp } from '@/contexts/AppContext';
import { markdownToHtml, openPrintablePdf } from '@/lib/printPdf';
import type { PaginationMeta, ResourceCategory, ResourceDetail, ResourceListItem } from '@/types/api';

const EMPTY_META: PaginationMeta = {
  page: 1,
  page_size: 20,
  total: 0,
  total_pages: 1,
};

export function ResourcesScreen() {
  const { t } = useTranslation(['portal', 'app']);
  const { language } = useApp();
  const [items, setItems] = useState<ResourceListItem[]>([]);
  const [categories, setCategories] = useState<ResourceCategory[]>([]);
  const [detail, setDetail] = useState<ResourceDetail | null>(null);
  const [selectedUuid, setSelectedUuid] = useState('');
  const [page, setPage] = useState(1);
  const [meta, setMeta] = useState<PaginationMeta>(EMPTY_META);
  const [keyword, setKeyword] = useState('');
  const [category, setCategory] = useState('');
  const [showOriginal, setShowOriginal] = useState(false);
  const [resolvingTranslation, setResolvingTranslation] = useState(false);

  const handlePDF = () => {
    if (!detail) return;

    const content = showOriginal ? detail.original_content_markdown : detail.display_content_markdown;
    const summaryHtml = detail.summary
      ? `<p><strong>${detail.summary}</strong></p><hr>`
      : '';

    openPrintablePdf({
      title: detail.title,
      metaLine: `${detail.category_label} · ${detail.published_at.slice(0, 10)}`,
      contentHtml: `${summaryHtml}${markdownToHtml(content)}`,
      footerText: 'Generated by Academy Linker · Resources',
    });
  };

  useEffect(() => {
    resourcesApi.getCategories({ audience_role: 'parent' }).then(res => {
      setCategories(res.data);
    }).catch(() => {});
  }, []);

  useEffect(() => {
    resourcesApi.getList({
      page,
      page_size: 20,
      audience_role: 'parent',
      category: category || undefined,
      keyword: keyword.trim() || undefined,
      sort: 'published_at_desc',
    }).then(res => {
      setItems(res.data);
      setMeta(res.meta);
      setSelectedUuid(prev => (res.data.some(item => item.uuid === prev) ? prev : res.data[0]?.uuid ?? ''));
    }).catch(() => {});
  }, [category, keyword, page]);

  useEffect(() => {
    if (!selectedUuid) {
      setDetail(null);
      setShowOriginal(false);
      return;
    }
    resourcesApi.getDetail(selectedUuid).then(res => {
      setDetail(res.data);
    }).catch(() => {});
  }, [selectedUuid]);

  useEffect(() => {
    setShowOriginal(false);
  }, [language, selectedUuid]);

  const toggleTranslation = async () => {
    if (!detail || detail.original_language === language) return;
    if (detail.translated_content_markdown || detail.translation_status === 'completed') {
      setShowOriginal(prev => !prev);
      return;
    }
    setResolvingTranslation(true);
    try {
      const res = await translations.resolve({ resource_type: 'resource', resource_uuid: detail.uuid });
      setDetail(prev => prev ? ({
        ...prev,
        display_content_markdown: res.data.display_content_markdown,
        original_content_markdown: res.data.original_content_markdown,
        translated_content_markdown: res.data.translated_content_markdown,
        display_language: res.data.display_language,
        original_language: res.data.original_language,
        translated_language: res.data.translated_language,
        translation_status: res.data.translation_status,
        translated_at: res.data.translated_at,
      }) : prev);
      setShowOriginal(false);
    } finally {
      setResolvingTranslation(false);
    }
  };

  return (
    <div>
      <div style={{ marginBottom: 24 }}>
        <div className="font-serif" style={{ fontSize: 26, color: 'var(--tx)', marginBottom: 6 }}>
          {t('resourcesTitle')}
        </div>
        <div style={{ fontSize: 14, color: 'var(--tx2)' }}>
          {t('resourcesSubtitle')} · {t('resourcesCount', { count: meta.total })}
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '320px 1fr', gap: 16 }}>
        <div className="card">
          <div style={{ display: 'grid', gap: 10, marginBottom: 14 }}>
            <input className="input-field" placeholder={t('searchResources')} value={keyword} onChange={e => { setPage(1); setKeyword(e.target.value); }} />
            <select className="input-field" value={category} onChange={e => { setPage(1); setCategory(e.target.value); }}>
              <option value="">{t('allCategories')}</option>
              {categories.map(item => <option key={item.key} value={item.key}>{item.label}</option>)}
            </select>
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {items.map(item => (
              <div
                key={item.uuid}
                className="card-sm"
                style={{ cursor: 'pointer', borderColor: selectedUuid === item.uuid ? 'var(--a1)' : undefined }}
                onClick={() => setSelectedUuid(item.uuid)}
              >
                <div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, marginBottom: 6 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--tx)' }}>{item.title}</div>
                  {item.is_pinned && <span className="badge" style={{ fontSize: 10 }}>{t('pinned')}</span>}
                </div>
                <div style={{ fontSize: 11, color: 'var(--tx3)', marginBottom: 6 }}>{item.category_label}</div>
                {item.summary && <div style={{ fontSize: 12, color: 'var(--tx2)', lineHeight: 1.6 }}>{item.summary}</div>}
              </div>
            ))}
            {items.length === 0 && (
              <div style={{ textAlign: 'center', color: 'var(--tx3)', fontSize: 13, padding: '40px 0' }}>
                {t('noResourcesFound')}
              </div>
            )}
          </div>

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 12 }}>
            <button className="btn-secondary" style={{ width: 'auto', padding: '8px 14px' }} disabled={page <= 1} onClick={() => setPage(prev => prev - 1)}>
              {t('previous')}
            </button>
            <button className="btn-secondary" style={{ width: 'auto', padding: '8px 14px' }} disabled={page >= meta.total_pages} onClick={() => setPage(prev => prev + 1)}>
              {t('next')}
            </button>
          </div>
        </div>

        <div className="card" style={{ minHeight: 520 }}>
          {detail ? (
            <>
              <div style={{ display: 'flex', justifyContent: 'space-between', gap: 12, marginBottom: 16 }}>
                <div>
                  <div className="font-serif" style={{ fontSize: 24, color: 'var(--tx)', marginBottom: 6 }}>{detail.title}</div>
                  <div style={{ fontSize: 12, color: 'var(--tx3)' }}>{detail.category_label} · {detail.published_at.slice(0, 10)}</div>
                  <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap', marginTop: 8 }}>
                    <span className="badge" style={{ fontSize: 10 }}>{detail.audience_role}</span>
                    <span className="badge" style={{ fontSize: 10 }}>{detail.display_language}</span>
                    {detail.translated_language && <span className="badge" style={{ fontSize: 10 }}>{detail.translated_language}</span>}
                    <span className="badge" style={{ fontSize: 10 }}>{detail.translation_status}</span>
                    {detail.external_url && <span className="badge" style={{ fontSize: 10 }}>{t('externalResource')}</span>}
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                  <TtsButton resourceType="resource" resourceUuid={detail.uuid} />
                  {detail.original_language !== language && (
                    <button className="btn-secondary" style={{ width: 'auto', padding: '8px 14px' }} onClick={() => void toggleTranslation()} disabled={resolvingTranslation}>
                      {resolvingTranslation ? '…' : showOriginal ? t('app:actions.showTranslation') : ((detail.translated_content_markdown || detail.display_language !== detail.original_language) ? t('app:actions.showOriginal') : t('app:actions.translate'))}
                    </button>
                  )}
                  <button
                    className="btn-secondary"
                    style={{ width: 'auto', padding: '8px 14px' }}
                    onClick={handlePDF}
                    disabled={!detail.display_content_markdown && !detail.original_content_markdown}
                  >
                    ⬇ {t('app:parentReports.downloadPdf')}
                  </button>
                  {detail.external_url && (
                    <a className="btn-secondary" style={{ width: 'auto', padding: '8px 14px', textDecoration: 'none' }} href={detail.external_url} target="_blank" rel="noreferrer">
                      {t('openLink')}
                    </a>
                  )}
                </div>
              </div>
              {detail.translated_at && (
                <div style={{ fontSize: 12, color: 'var(--tx3)', marginBottom: 12 }}>
                  {t('app:resourceDetail.translatedAt', { date: detail.translated_at.slice(0, 10) })}
                </div>
              )}
              {detail.cover_image_url && (
                <div style={{ marginBottom: 16 }}>
                  <img
                    src={detail.cover_image_url}
                    alt={detail.title}
                    style={{ width: '100%', maxHeight: 220, objectFit: 'cover', borderRadius: 12, border: '1px solid var(--bd)' }}
                  />
                </div>
              )}
              {detail.summary && <div style={{ fontSize: 13, color: 'var(--tx2)', lineHeight: 1.7, marginBottom: 16 }}>{detail.summary}</div>}
              <div style={{ fontSize: 13, color: 'var(--tx2)', lineHeight: 1.75, whiteSpace: 'pre-wrap' }}>
                {showOriginal ? detail.original_content_markdown : detail.display_content_markdown}
              </div>
            </>
          ) : (
            <div style={{ textAlign: 'center', color: 'var(--tx3)', fontSize: 13, padding: '100px 0' }}>
              {t('selectResource')}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
