function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function inlineMarkdownToHtml(value: string): string {
  return escapeHtml(value).replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
}

export function markdownToHtml(markdown: string): string {
  const lines = markdown.split('\n');
  const output: string[] = [];
  let inUl = false;
  let inOl = false;

  for (const line of lines) {
    const isBullet = line.startsWith('- ') || line.startsWith('* ');
    const isNumbered = /^\d+\./.test(line);

    if (!isBullet && inUl) {
      output.push('</ul>');
      inUl = false;
    }
    if (!isNumbered && inOl) {
      output.push('</ol>');
      inOl = false;
    }

    if (!line.trim()) {
      output.push('<br>');
      continue;
    }
    if (/^---+$/.test(line)) {
      output.push('<hr>');
      continue;
    }
    if (line.startsWith('# ')) {
      output.push(`<h1>${escapeHtml(line.slice(2))}</h1>`);
      continue;
    }
    if (line.startsWith('## ')) {
      output.push(`<h2>${escapeHtml(line.slice(3))}</h2>`);
      continue;
    }
    if (line.startsWith('### ')) {
      output.push(`<h3>${escapeHtml(line.slice(4))}</h3>`);
      continue;
    }
    if (isBullet) {
      if (!inUl) {
        output.push('<ul>');
        inUl = true;
      }
      output.push(`<li>${inlineMarkdownToHtml(line.slice(2))}</li>`);
      continue;
    }
    if (isNumbered) {
      if (!inOl) {
        output.push('<ol>');
        inOl = true;
      }
      output.push(`<li>${inlineMarkdownToHtml(line.replace(/^\d+\.\s*/, ''))}</li>`);
      continue;
    }

    output.push(`<p>${inlineMarkdownToHtml(line)}</p>`);
  }

  if (inUl) output.push('</ul>');
  if (inOl) output.push('</ol>');

  return output.join('\n');
}

type PrintableDocumentOptions = {
  title: string;
  metaLine?: string;
  contentHtml: string;
  footerText?: string;
};

export function openPrintablePdf({
  title,
  metaLine = '',
  contentHtml,
  footerText = 'Generated by Academy Linker',
}: PrintableDocumentOptions) {
  const win = window.open('', '_blank', 'width=900,height=700');
  if (!win) return;

  win.document.write(`<!DOCTYPE html>
<html><head>
  <meta charset="utf-8">
  <title>${escapeHtml(title)}</title>
  <style>
    * { box-sizing: border-box; }
    body { font-family: Georgia, 'Times New Roman', serif; max-width: 800px; margin: 40px auto; color: #2A3560; line-height: 1.85; font-size: 14px; padding: 0 20px; }
    .report-header { border-bottom: 3px solid #E8614E; padding-bottom: 18px; margin-bottom: 28px; }
    .report-header h1 { font-size: 28px; margin: 0 0 6px; color: #2A3560; }
    .report-header .meta { color: #7A6A8C; font-size: 12px; font-style: italic; }
    h2 { font-size: 18px; color: #2A3560; border-bottom: 1.5px solid #E8614E; padding-bottom: 5px; margin-top: 28px; }
    h3 { font-size: 15px; color: #4A5568; margin-top: 18px; }
    p  { color: #4A5568; margin: 6px 0; }
    ul, ol { color: #4A5568; padding-left: 22px; }
    li { margin: 4px 0; }
    strong { color: #2A3560; }
    hr { border: none; border-top: 1px solid #E0D0C0; margin: 20px 0; }
    .footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid #E0D0C0; font-size: 11px; color: #B8A8C8; text-align: center; }
    @media print { body { margin: 20mm 25mm; } .footer { position: fixed; bottom: 10mm; left: 0; right: 0; } }
  </style>
</head>
<body>
  <div class="report-header">
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">${escapeHtml(metaLine)}</div>
  </div>
  ${contentHtml}
  <div class="footer">${escapeHtml(footerText)}</div>
</body>
</html>`);

  win.document.close();
  win.focus();
  window.setTimeout(() => win.print(), 600);
}
